// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { EthWord$Type } from "./EthWord";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EthWord"]: EthWord$Type;
    ["contracts/EthWord.sol:EthWord"]: EthWord$Type;
  }

  interface ContractTypesMap {
    ["EthWord"]: GetContractReturnType<EthWord$Type["abi"]>;
    ["contracts/EthWord.sol:EthWord"]: GetContractReturnType<EthWord$Type["abi"]>;
  }
}
